# fly.toml app configuration file generated for anime4k-webgpu-demo on 2023-11-29T15:47:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anime4k-webgpu-demo"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
